version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.3.1

workflows:
  use-another-yml:
    jobs:
      - continuation/continue:
          configuration_path: ./.circleci/hello.yml
