version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.3.1

jobs:
  build:
    executor: continuation/default
    steps:
      - checkout
      - run:
          command: |
            cd .circleci
            cat header.yml executors.yml jobs.yml workflows.yml > pipeline.yml
      - continuation/continue:
          configuration_path: .circleci/pipeline.yml
